/* 
	implementation of the tables - foreign keys
*/


                                                                                                                                              
ALTER TABLE PRESIDENT
    ADD CONSTRAINT FOR_KEY_PRES 
	FOREIGN KEY (STATE_BORN) REFERENCES STATE(STATE_NAME);

ALTER TABLE PRES_MARRIAGE
    ADD CONSTRAINT FOR_KEY_PRESMAR 
	FOREIGN KEY (PRES_NAME) REFERENCES PRESIDENT(PRES_NAME);

ALTER TABLE ADMINISTRATION
    ADD CONSTRAINT FOR_KEY_ADMIN
        FOREIGN KEY (PRES_NAME) REFERENCES PRESIDENT(PRES_NAME);

ALTER TABLE ADMIN_PR_VP
    ADD CONSTRAINT FOR_KEY_ADMVP 
	FOREIGN KEY (ADMIN_NR,PRES_NAME) REFERENCES ADMINISTRATION(ADMIN_NR,PRES_NAME);

ALTER TABLE PRES_HOBBY
    ADD CONSTRAINT FOR_KEY_HOBBY 
	FOREIGN KEY (PRES_NAME) REFERENCES PRESIDENT(PRES_NAME);


